import { chromium } from 'playwright';
const B='http://localhost:3000';
const b = await chromium.launch({ headless:true });
const ctx = await b.newContext();
const p = await ctx.newPage();
const u = `dredz_${Math.floor(Math.random()*1e7)}`;
await p.request.post(`${B}/api/auth/register`, { data: { username:u, email:u+'@t.com', password:'Pass123!', role:'candidate' } });
await p.goto(`${B}/dashboard/candidate`, { waitUntil:'networkidle', timeout:30000 });
await p.waitForTimeout(900);
await p.screenshot({ path:'scripts/_cd.png' });
await b.close(); console.log('done '+u);
